### ISSUE TITLE
Client side part

### ISSUE THREAD

**Issue by Christopher2K** [Bright-Hustle/adonis-transmit#1]
Hey!

First of all, thanks for this package! Can you post some instruction on how to use on client side? Looking at the source code I feel like we're not supposed to use this using the `EventSource` object!

Thanks!

**Comment by CodeSyncr** [comment]
https://www.npmjs.com/package/@brighthustle/transmit-client

Use This Package 

import { Transmit } from '@brighthustle/transmit-client'

const transmit = new Transmit({
  baseUrl: 'http://localhost:3333',
})

transmit.listenOn<{ message: string }>('chat/1', (payload) => {
  console.log(payload.message)
})
